import type { ResearchPlan, Synthesis, EvidenceFinding, EvidenceMemo } from '../types';
import { dbGet } from '../lib/fileManager';
import type { AgentOutput, StageRecord } from '../lib/pipelineTypes';
import type { WorkbenchAgentContext } from '../lib/workbenchAgentContext';
import { checkAborted, emitReasoning, buildAgentOutput } from '../lib/workbenchAgentContext';

async function loadPlan(tipId: string): Promise<ResearchPlan | null> {
  const raw = await dbGet(`research-plan/${tipId}`);
  if (!raw) return null;
  try {
    return JSON.parse(raw as string) as ResearchPlan;
  } catch {
    return null;
  }
}

async function loadEvidence(tipId: string): Promise<{ external: EvidenceFinding[]; internal: EvidenceFinding[] }> {
  const extRaw = await dbGet(`external-evidence/${tipId}`);
  const intRaw = await dbGet(`internal-evidence/${tipId}`);
  const external = extRaw ? (JSON.parse(extRaw as string).findings as EvidenceFinding[]) || [] : [];
  const internal = intRaw ? (JSON.parse(intRaw as string).findings as EvidenceFinding[]) || [] : [];
  return { external, internal };
}

async function loadSynthesis(tipId: string): Promise<Synthesis | null> {
  const raw = await dbGet(`synthesis/${tipId}`);
  if (!raw) return null;
  try {
    return JSON.parse(raw as string) as Synthesis;
  } catch {
    return null;
  }
}

/**
 * Build a markdown evidence memo from the approved synthesis.
 * Pure code — no LLM call.
 */
export function buildEvidenceMemoMarkdown(
  plan: ResearchPlan,
  synthesis: Synthesis,
  external: EvidenceFinding[],
  internal: EvidenceFinding[]
): string {
  const lines: string[] = [];

  lines.push('# Evidence Memo');
  lines.push('');
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push('');

  // Tip
  lines.push('## Original Tip');
  lines.push('');
  lines.push(plan.tipId ? `(Tip ID: ${plan.tipId})` : '');
  lines.push('');

  // Research questions
  lines.push('## Research Questions');
  lines.push('');
  for (const sc of plan.subClaims) {
    lines.push(`### ${sc.question}`);
    lines.push(`**Claim:** ${sc.claim}`);
    lines.push('');
  }

  // Findings per sub-claim
  lines.push('---');
  lines.push('');
  lines.push('## Findings by Sub-Claim');
  lines.push('');

  for (const entry of synthesis.entries) {
    const sc = plan.subClaims.find((c) => c.id === entry.subClaimId);
    lines.push(`### ${sc?.question || entry.subClaimId}`);
    lines.push('');

    if (entry.supportingSources.length > 0) {
      lines.push('**Supporting Sources:**');
      lines.push('');
      for (const src of entry.supportingSources) {
        lines.push(`- **${src.sourceType.toUpperCase()}:** ${src.ref}`);
        lines.push(`  > ${src.passage.replace(/\n/g, ' ').slice(0, 300)}`);
        lines.push('');
      }
    } else {
      lines.push('*No supporting sources found.*');
      lines.push('');
    }

    if (entry.contradictions.length > 0) {
      lines.push('**Contradictions:**');
      lines.push('');
      for (const c of entry.contradictions) {
        lines.push(`- **[CONTRADICTION]** **${c.between.join(' vs ')}:** ${c.description}`);
      }
      lines.push('');
    }

    if (entry.gaps.length > 0) {
      lines.push('**Gaps:**');
      lines.push('');
      for (const g of entry.gaps) {
        lines.push(`- **[GAP]** ${g}`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Full source attribution
  lines.push('## Source Attribution');
  lines.push('');

  const webSources = external.filter((f) => f.sourceUrl);
  if (webSources.length > 0) {
    lines.push('### Web Sources');
    lines.push('');
    const uniqueUrls = [...new Set(webSources.map((f) => f.sourceUrl))];
    for (const url of uniqueUrls) {
      lines.push(`- ${url}`);
    }
    lines.push('');
  }

  const docSources = internal.filter((f) => f.documentRef);
  if (docSources.length > 0) {
    lines.push('### Document Sources');
    lines.push('');
    const uniqueRefs = [...new Set(docSources.map((f) => f.documentRef))];
    for (const ref of uniqueRefs) {
      lines.push(`- ${ref}`);
    }
    lines.push('');
  }

  // Confidence summary
  lines.push('## Confidence Summary');
  lines.push('');
  for (const entry of synthesis.entries) {
    const sc = plan.subClaims.find((c) => c.id === entry.subClaimId);
    const hasSupport = entry.supportingSources.length > 0;
    const hasContradiction = entry.contradictions.length > 0;
    let confidence = 'low';
    if (hasSupport && !hasContradiction) confidence = 'high';
    else if (hasSupport) confidence = 'medium';

    lines.push(`- ${sc?.question || entry.subClaimId}: **${confidence.toUpperCase()}**`);
  }
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('*This memo was generated by the AI Investigative Workbench. All claims are attributed to the sources listed above. Human review is required before publication.*');
  lines.push('');

  return lines.join('\n');
}

export interface AssembleResult {
  success: boolean;
  markdown?: string;
  memo?: EvidenceMemo;
  error?: string;
}

/**
 * Assemble the full evidence memo from stored pipeline outputs.
 */
export async function assembleEvidenceMemo(tipId: string): Promise<AssembleResult> {
  try {
    const plan = await loadPlan(tipId);
    if (!plan) {
      return { success: false, error: `Research plan not found for tipId: ${tipId}` };
    }

    const synthesis = await loadSynthesis(tipId);
    if (!synthesis) {
      return { success: false, error: 'Synthesis not found' };
    }

    const { external, internal } = await loadEvidence(tipId);

    const markdown = buildEvidenceMemoMarkdown(plan, synthesis, external, internal);

    const confidenceSummary: Record<string, 'high' | 'medium' | 'low'> = {};
    for (const entry of synthesis.entries) {
      const hasSupport = entry.supportingSources.length > 0;
      const hasContradiction = entry.contradictions.length > 0;
      confidenceSummary[entry.subClaimId] = hasSupport && !hasContradiction ? 'high' : hasSupport ? 'medium' : 'low';
    }

    const memo: EvidenceMemo = {
      tip: { id: plan.tipId, text: '', createdAt: plan.createdAt },
      researchPlan: plan,
      findings: synthesis.entries,
      contradictions: synthesis.entries.flatMap((e) => e.contradictions),
      gaps: synthesis.entries.flatMap((e) => e.gaps),
      confidenceSummary,
      generatedAt: new Date().toISOString(),
    };

    return { success: true, markdown, memo };
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    return { success: false, error };
  }
}

/**
 * AgentFn implementation of report assembler.
 * Receives tipId via `ctx.currentDraft`.
 */
export async function assembleEvidenceMemoAgent(
  ctx: WorkbenchAgentContext,
  onReasoningChunk: (chunk: string) => void,
  onUpdate?: (partial: Partial<StageRecord>) => void
): Promise<AgentOutput> {
  checkAborted(ctx);
  const tipId = ctx.tipId || ctx.currentDraft;

  emitReasoning('[ReportAssembler] Assembling evidence memo...', onReasoningChunk, onUpdate);

  const plan = await loadPlan(tipId);
  if (!plan) {
    throw new Error(`Research plan not found for tipId: ${tipId}`);
  }

  const synthesis = await loadSynthesis(tipId);
  if (!synthesis) {
    throw new Error('Synthesis not found');
  }

  const { external, internal } = await loadEvidence(tipId);

  const markdown = buildEvidenceMemoMarkdown(plan, synthesis, external, internal);

  const confidenceSummary: Record<string, 'high' | 'medium' | 'low'> = {};
  for (const entry of synthesis.entries) {
    const hasSupport = entry.supportingSources.length > 0;
    const hasContradiction = entry.contradictions.length > 0;
    confidenceSummary[entry.subClaimId] = hasSupport && !hasContradiction ? 'high' : hasSupport ? 'medium' : 'low';
  }

  const memo: EvidenceMemo = {
    tip: { id: plan.tipId, text: '', createdAt: plan.createdAt },
    researchPlan: plan,
    findings: synthesis.entries,
    contradictions: synthesis.entries.flatMap((e) => e.contradictions),
    gaps: synthesis.entries.flatMap((e) => e.gaps),
    confidenceSummary,
    generatedAt: new Date().toISOString(),
  };

  emitReasoning('[ReportAssembler] Memo assembled.', onReasoningChunk, onUpdate);

  return buildAgentOutput({
    draft: markdown,
    reasoning: `Assembled evidence memo for tip ${tipId} with ${synthesis.entries.length} entries`,
    metadata: { memo },
  });
}
